export const specialitiesData = [
  { id: '1', title: 'Software Development' },
  { id: '2', title: 'Digital Marketing' },
  { id: '3', title: 'Career Guidance' },
  { id: '4', title: 'Startup Mentorship' },
  { id: '5', title: 'Data Science' },
  { id: '6', title: 'UI/UX Design' },
  { id: '7', title: 'Finance' },
  { id: '8', title: 'Legal Consultation' },
  { id: '9', title: 'Public Speaking' },
  { id: '10', title: 'Content Creation' },
];
export const expertsData = [
  {
    id: '1',
    name: 'Rahul Sharma',
    image: require('../assets/img/rahul.png'),
    specialty: '1',
    phone: '+91 9876543210',
    email: 'rahul.sharma@expertbook.com',
    experience: '8 Years',
    rating: 4.8,
    fee:999,
    expertise: 'Software Development',
  },
  {
    id: '2',
    name: 'Priya Verma',
    image: require('../assets/img/priya.png'),
    specialty: '2',
    phone: '+91 9876543211',
    email: 'priya.verma@expertbook.com',
    experience: '6 Years',
    rating: 4.7,
    fee:799,
    expertise: 'Digital Marketing',
  },
  {
    id: '3',
    name: 'Amit Patel',
    image: require('../assets/img/amit.png'),
    specialty: '3',
    phone: '+91 9876543212',
    email: 'amit.patel@expertbook.com',
    experience: '10 Years',
    rating: 4.9,
    fee:1199,
    expertise: 'Career Guidance',
  },
  {
    id: '4',
    name: 'Neha Singh',
    image: require('../assets/img/neha.png'),
    specialty: '4',
    phone: '+91 9876543213',
    email: 'neha.singh@expertbook.com',
    experience: '7 Years',
    rating: 4.6,
    fee:1499,
    expertise: 'Startup Mentorship',
  },
  {
    id: '5',
    name: 'Vikram Joshi',
    image: require('../assets/img/vikram.png'),
    specialty: '5',
    phone: '+91 9876543214',
    email: 'vikram.joshi@expertbook.com',
    experience: '9 Years',
    rating: 4.8,
    fee:1299,
    expertise: 'Data Science',
  },
  {
    id: '6',
    name: 'Ananya Gupta',
    image: require('../assets/img/ananya.png'),
    specialty: '6',
    phone: '+91 9876543215',
    email: 'ananya.gupta@expertbook.com',
    experience: '5 Years',
    rating: 4.7,
    fee:899,
    expertise: 'UI/UX Design',
  },
  {
    id: '7',
    name: 'Rohit Mehta',
    image: require('../assets/img/rohit.png'),
    specialty: '7',
    phone: '+91 9876543216',
    email: 'rohit.mehta@expertbook.com',
    experience: '11 Years',
    rating: 4.9,
    fee:1599,
    expertise: 'Finance',
  },
  {
    id: '8',
    name: 'Sneha Kapoor',
    image: require('../assets/img/sneha.png'),
    specialty: '8',
    phone: '+91 9876543217',
    email: 'sneha.kapoor@expertbook.com',
    experience: '8 Years',
    rating: 4.8,
    fee:1799,
    expertise: 'Legal Consultation',
  },
  {
    id: '9',
    name: 'Arjun Nair',
    image: require('../assets/img/arjun.png'),
    specialty: '9',
    phone: '+91 9876543218',
    email: 'arjun.nair@expertbook.com',
    experience: '6 Years',
    rating: 4.7,
    fee:999,
    expertise: 'Public Speaking',
  },
  {
    id: '10',
    name: 'Kavya Reddy',
    image: require('../assets/img/kavya.png'),
    specialty: '10',
    phone: '+91 9876543219',
    email: 'kavya.reddy@expertbook.com',
    experience: '7 Years',
    rating: 4.8,
    fee:799,
    expertise: 'Content Creation',
  },
];