export const specialitiesData = [
  { id: '1', title: 'Software Development' },
  { id: '2', title: 'Digital Marketing' },
  { id: '3', title: 'Career Guidance' },
  { id: '4', title: 'Startup Mentorship' },
  { id: '5', title: 'Data Science' },
  { id: '6', title: 'UI/UX Design' },
  { id: '7', title: 'Finance' },
  { id: '8', title: 'Legal Consultation' },
  { id: '9', title: 'Public Speaking' },
  { id: '10', title: 'Content Creation' },
];
export const expertsData = [
  {
    id: '1',
    name: 'Rahul Sharma',
    image: require('../assets/img/rahul.png'),
    specialty: '1',
    phone: '+91 9876543210',
    email: 'rahul.sharma@expertbook.com',
    experience: '8 Years',
    rating: 4.8,
    fee:999,
    expertise: 'Software Development',
    clients: "120+",
    reviews: "320",
    about: "Rahul Sharma is an experienced Software Development mentor with over 8 years of industry experience helping students and professionals build scalable applications and prepare for technical interviews."
  },
  {
    id: '2',
    name: 'Priya Verma',
    image: require('../assets/img/priya.png'),
    specialty: '2',
    phone: '+91 9876543211',
    email: 'priya.verma@expertbook.com',
    experience: '6 Years',
    rating: 4.7,
    fee:799,
    expertise: 'Digital Marketing',
    clients: "210+",
    reviews: "165",
    about:"Priya Verma is a Digital Marketing consultant with 6 years of experience in SEO, social media marketing, and performance campaigns. She helps businesses and creators grow their online presence.",


  },
  {
    id: '3',
    name: 'Amit Patel',
    image: require('../assets/img/amit.png'),
    specialty: '3',
    phone: '+91 9876543212',
    email: 'amit.patel@expertbook.com',
    experience: '10 Years',
    rating: 4.9,
    fee:1199,
    expertise: 'Career Guidance',
    clients: "320+",
    reviews: "245",
    about:"Amit Patel has 10 years of experience in Career Guidance. He has mentored hundreds of students and professionals in choosing the right career path, preparing resumes, and cracking interviews.",
  },
  {
    id: '4',
    name: 'Neha Singh',
    image: require('../assets/img/neha.png'),
    specialty: '4',
    phone: '+91 9876543213',
    email: 'neha.singh@expertbook.com',
    experience: '7 Years',
    rating: 4.6,
    fee:1499,
    expertise: 'Startup Mentorship',
    clients: "180+",
    reviews: "140",
    about:"Neha Singh is a Startup Mentor with 7 years of experience helping entrepreneurs validate ideas, create business models, and scale successful startups.",

  },
  {
    id: '5',
    name: 'Vikram Joshi',
    image: require('../assets/img/vikram.png'),
    specialty: '5',
    phone: '+91 9876543214',
    email: 'vikram.joshi@expertbook.com',
    experience: '9 Years',
    rating: 4.8,
    fee:1299,
    expertise: 'Data Science',
    clients: "290+",
    reviews: "210",
    about:"Vikram Joshi is a Data Science expert with 9 years of experience in machine learning, AI, and analytics. He mentors learners and professionals in building practical data science projects.",
  },
  {
    id: '6',
    name: 'Ananya Gupta',
    image: require('../assets/img/ananya.png'),
    specialty: '6',
    phone: '+91 9876543215',
    email: 'ananya.gupta@expertbook.com',
    experience: '5 Years',
    rating: 4.7,
    fee:899,
    expertise: 'UI/UX Design',
    clients: "170+",
    reviews: "135",
    about:"Ananya Gupta is a UI/UX Design specialist with 5 years of experience designing intuitive web and mobile applications. She guides designers in creating user-friendly digital products.",

  },
  {
    id: '7',
    name: 'Rohit Mehta',
    image: require('../assets/img/rohit.png'),
    specialty: '7',
    phone: '+91 9876543216',
    email: 'rohit.mehta@expertbook.com',
    experience: '11 Years',
    rating: 4.9,
    fee:1599,
    expertise: 'Finance',
    clients: "360+",
    reviews: "275",
    about:"Rohit Mehta is a Finance consultant with 11 years of experience in investment planning, personal finance, and wealth management. He provides practical financial advice for individuals and businesses.",

  },
  {
    id: '8',
    name: 'Sneha Kapoor',
    image: require('../assets/img/sneha.png'),
    specialty: '8',
    phone: '+91 9876543217',
    email: 'sneha.kapoor@expertbook.com',
    experience: '8 Years',
    rating: 4.8,
    fee:1799,
    expertise: 'Legal Consultation',
    clients: "240+",
    reviews: "190",
    about:"Sneha Kapoor is a Legal Consultant with 8 years of experience specializing in business law, contracts, and legal compliance. She offers clear and reliable legal guidance to clients.",
  },
  {
    id: '9',
    name: 'Arjun Nair',
    image: require('../assets/img/arjun.png'),
    specialty: '9',
    phone: '+91 9876543218',
    email: 'arjun.nair@expertbook.com',
    experience: '6 Years',
    rating: 4.7,
    fee:999,
    expertise: 'Public Speaking',
    clients: "200+",
    reviews: "155",
    about:"Arjun Nair is a Public Speaking coach with 6 years of experience helping professionals, students, and entrepreneurs improve communication skills and stage confidence.",
  },
  {
    id: '10',
    name: 'Kavya Reddy',
    image: require('../assets/img/kavya.png'),
    specialty: '10',
    phone: '+91 9876543219',
    email: 'kavya.reddy@expertbook.com',
    experience: '7 Years',
    rating: 4.8,
    fee:799,
    expertise: 'Content Creation',
    clients: "220+",
    reviews: "170",
    about:"Kavya Reddy is a Content Creation expert with 7 years of experience in branding, social media content, and storytelling. She helps creators and businesses produce engaging digital content."
  },
];